invclc/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('index/', views.index_view, name='index'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('update_invoice/<int:invoice_id>/', views.update_invoice, name='update_invoice'),
    path('delete_invoice/<int:invoice_id>/', views.delete_invoice, name='delete_invoice'),
    path('pay_invoice/<int:invoice_id>/', views.pay_invoice, name='pay_invoice'),
    path('payment_invoice/<int:payment_id>/', views.payment_invoice, name='payment_invoice'),
    # path('entry/',views.entrydata, name="entry"),
    path('update/', views.update_view, name='update'),
    path('delete/', views.delete_page, name='delete'),
    path('check/<int:id>', views.check_view, name='check'),
    path('statics/', views.staticspage_view, name='statics'),
    # path('create/', views.create_view, name='create'),
    path('update_view/<int:pk>/', views.update_view, name='update'),
    # path('payment/<int:payment_id>',views.payment_view, name="payment"),
    # path('edit/<int:id>',views.edit_view, name='edit'),
    # path('delete_view/<int:pk>/', views.delete_view, name='delete_view'),
    path('import-export/', views.import_view, name='import-export'),
    
    path('csv/', views.exports_to_csv, name='exports_to_csv'),
    path('xlsx/', views.exports_to_xlsx, name='exports_to_xlsx'),
    path('json/', views.exports_to_json, name='exports_to_json'),
    
    path('checkmore/', views.checkmore_view, name='checkmore'),
    path('paymore/', views.paymore_view, name='paymore'),
    path('updatemore/', views.updatemore_view, name='updatemore'),
    path('unpaid_debt/', views.unpaid_debt, name='unpaid_debt'),

    path('upload_csv/', views.upload_csv, name='upload_csv'),
    path('empty_csv/',views.empty_csv,name='empty_csv'),
    path('empty_xlsx/',views.empty_xlsx,name='empty_xlsx'),
    path('adminacess/',views.admin_access,name='adminacess'),
    path('invite/',views.invite_user,name='invite'),
    
    path('process_invite/',views.process_invite,name='process_invite'),
    
    path('connect/',views.connect_view,name='connect'),
    path('create_medical/',views.create_medical_record,name="create_medical"),
    path('search/',views.medical_search,name="medical_search"),

    path('get_yearly_data/', views.get_yearly_data, name='get_yearly_data'),
    path('get_monthly_data/', views.get_monthly_data, name='get_monthly_data'), 
    path('get_total_sum/', views.get_total_sum, name='get_total_sum'),
    path('api/data', views.get_data, name='get_data'),

]

medregia/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('authentication.urls')),
    path('',include('invclc.urls')),   
]

invclc/models.py
from django.db import models
from django.utils import timezone
from authentication.models import CustomUser
from datetime import timedelta
from django.db.models.signals import pre_delete,pre_save,post_save, post_delete
from django.dispatch import receiver



class Invoice(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, related_name='invoices')
    pharmacy_name = models.CharField(max_length=100)
    invoice_number = models.CharField(max_length=50)
    invoice_date = models.DateField(default=timezone.now)
    invoice_amount = models.DecimalField(max_digits=10, decimal_places=2)
    balance_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    payment_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    today_date = models.DateField(default=timezone.now)
    current_time = models.TimeField(null=True, blank=True)
    updated_by = models.CharField(max_length=20, null=True, blank=True)
    collaborator_invoice = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, related_name='collaborator_invoices')

    dl_number1 = models.CharField(max_length=100, blank=True, null=True)
    dl_number2 = models.CharField(max_length=100, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.balance_amount = self.invoice_amount - self.payment_amount
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.user}"

    
class DeletedInvoice(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE,null=True)
    pharmacy = models.CharField(max_length=100)
    number = models.CharField(max_length=50)
    date = models.DateField(default=timezone.now)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    balance = models.DecimalField(max_digits=10, decimal_places=2 ,null=True, blank=True)
    payment = models.DecimalField(max_digits=10, decimal_places=2)
    today_date = models.DateField(default=timezone.now)
    
    def __str__(self):
        return f"{self.pharmacy}-{self.today_date}"
    
class ModifiedInvoice(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE,null=True)
    modified_pharmacy = models.CharField(max_length=100)
    modified_Invoice_number = models.CharField(max_length=50)
    modified_Invoice_date = models.DateField(default=timezone.now)
    modified_Total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    modified_balance = models.DecimalField(max_digits=10, decimal_places=2 ,null=True, blank=True)
    modified_payment = models.DecimalField(max_digits=10, decimal_places=2)
    modified_today_date = models.DateField(default=timezone.now)
    
    def __str__(self):
        
        return f"{self.modified_pharmacy}-{self.modified_today_date}"
    
class TrackingPayment(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE,null=True)
    Medical_name = models.CharField(max_length = 100)
    Bill_no = models.CharField(max_length = 100,null=True)
    Medical_payments = models.DecimalField(max_digits=20, decimal_places=2)
    payment_date = models.DateField(default=timezone.now)
    paying_amount = models.DecimalField(max_digits = 20 ,decimal_places=2, null=True)
    
    def __str__(self):
        return f"{self.user} - {self.Medical_payments} - {self.payment_date}"
    

class Invitation(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE,null=True)
    mail_sendername = models.CharField(max_length = 20)
    mail_receiver_name = models.CharField(max_length = 20)
    mail_receiver_email = models.EmailField()
    mail_receiver_phonenumber = models.CharField(max_length=15)
    mail_receiver_position = models.CharField(max_length=15 ,null=True)

@receiver(pre_delete, sender=Invoice)
def delete_tracking_payments(sender, instance, **kwargs):
    TrackingPayment.objects.filter(Medical_name=instance.pharmacy_name).delete()
    
@receiver(pre_save, sender=Invoice)
def update_tracking_payments(sender, instance, **kwargs):
    if instance.pk:
        original_instance = Invoice.objects.get(pk=instance.pk)
        # Check if the pharmacy_name has been modified
        if instance.pharmacy_name != original_instance.pharmacy_name:
            # Update the corresponding Medical_name in TrackingPayment
            TrackingPayment.objects.filter(Medical_name=original_instance.pharmacy_name, user=instance.user).update(Medical_name=instance.pharmacy_name)

invclc/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils.http import urlencode
from .models import Invoice,DeletedInvoice,ModifiedInvoice,TrackingPayment,Invitation
from .forms import InvoiceForm
from django.http import JsonResponse,HttpResponseServerError,HttpResponse,HttpResponseBadRequest,HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt ,csrf_protect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q,F
from django.utils import timezone
from authentication.models import CustomUser,Person,Notification,RegisterMedicals,ConnectMedicals
from datetime import datetime
import csv
import json
from django.utils import timezone
from django.views.decorators.http import require_POST,require_GET
from django.core.management import call_command
from decimal import Decimal
from openpyxl import Workbook
from tablib import Dataset
from .forms import UploadFileForm
from django.core.serializers import serialize
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.conf import settings
from itsdangerous import URLSafeSerializer,BadSignature
import openpyxl
import logging
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from .utils import generate_tempno,RegisterUserTempNo
from authentication.service import SendNotification

from django.db.models import Sum
from calendar import month_name

logger = logging.getLogger(__name__)
def upload_csv(request):
    checked_username = None
    senderName = None

    try:
        # Get all notifications sent to the current user that have been read
        read_notifications = Notification.objects.filter(receiver=request.user, is_read=True)
        
        # Loop through each read notification
        for notification in read_notifications:
            # Get the username of the sender of the notification
            sender_username = notification.sender.username
            # Get the username of the receiver of the notification (current user)
            receiver_username = notification.receiver.username
            
            # Find all staff users with the same username as the sender
            staff_senders = CustomUser.objects.filter(username=sender_username, is_staff=True)
            # Get the non-staff user (current user) with the specified username
            normal_user = CustomUser.objects.get(username=receiver_username, is_staff=False)
            
            # Loop through each staff user with the sender's username
            for user in staff_senders:
                sender = user.username

                try:
                    # Get the staff user with the current username
                    senderName = CustomUser.objects.get(username=sender, is_staff=True)
                    # Get the non-staff user (current user)
                    receiverName = CustomUser.objects.get(username=normal_user.username, is_staff=False)

                    if receiverName and senderName:
                        # Store the username of the current non-staff user
                        checked_username = receiverName.username
                except Exception as user_error:
                    # Handle exceptions that occur while processing a specific user
                    messages.error(request, user_error)
    except Exception as general_error:  
        # Handle exceptions that occur while processing notifications
        messages.error(request, "Something went wrong while exporting JSON: " + str(general_error))
        return JsonResponse({'error': "Something went wrong while processing notifications"}, status=500)

    if request.method == 'POST' and request.FILES.get('file'):
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            file = request.FILES['file']
            if file.name.endswith('.csv'):
                try:
                    csv_data = file.read().decode('utf-8').splitlines()
                    csv_reader = csv.DictReader(csv_data)

                    current_user = request.user

                    for row in csv_reader:
                        # Convert date string to datetime object
                        try:
                            invoice_date = datetime.strptime(row['invoice_date'], '%d/%m/%Y').date()
                        except ValueError:
                            invoice_date = datetime.strptime(row['invoice_date'], '%d-%m-%Y').date()

                        # Convert string values to integers
                        invoice_amount = int(row['invoice_amount'])
                        payment_amount = int(row['payment_amount'])
                        invoice_numbers = row['invoice_number']
                        invoice_dl_number1 = int(row['dl_number1'])
                        invoice_dl_number2 = int(row['dl_number2'])

                        # Calculate balance amount
                        balance_amount = invoice_amount - payment_amount

                        # Get the current date and time
                        current_date = datetime.now().date()
                        current_time = datetime.now().time()

                        # Create Invoice object for each row in the CSV file
                        if str(request.user) == checked_username:
                            check_invoice_number = Invoice.objects.filter(user=senderName, invoice_number=invoice_numbers)
                            if check_invoice_number.exists():
                                return JsonResponse({'error': 'This Invoice Already Exists in Your Medical'}, status=400)

                            invoice = Invoice.objects.create(
                                user=senderName,
                                pharmacy_name=row['pharmacy_name'],
                                invoice_number=row['invoice_number'],
                                invoice_date=invoice_date,
                                dl_number1=invoice_dl_number1,
                                dl_number2=invoice_dl_number2,
                                invoice_amount=invoice_amount,
                                payment_amount=payment_amount,
                                balance_amount=balance_amount,
                                today_date=current_date,  # Use current date
                                current_time=current_time,  # Use current time
                                updated_by=row['updated_by']
                            )
                        else:
                            check_invoice = Invoice.objects.filter(user=current_user, invoice_number=invoice_numbers)
                            if check_invoice.exists():
                                return JsonResponse({'error': 'This Invoice Already Exists in Your Medical'}, status=400)

                            invoice = Invoice.objects.create(
                                user=current_user,
                                pharmacy_name=row['pharmacy_name'],
                                invoice_number=row['invoice_number'],
                                invoice_date=invoice_date,
                                dl_number1=invoice_dl_number1,
                                dl_number2=invoice_dl_number2,
                                invoice_amount=invoice_amount,
                                payment_amount=payment_amount,
                                balance_amount=balance_amount,
                                today_date=current_date,  # Use current date
                                current_time=current_time,  # Use current time
                                updated_by=row['updated_by']
                            )

                    invoice.save()
                    return JsonResponse({'message': 'CSV Data uploaded successfully'}, status=200)
                except Exception as e:
                    logger.exception("Error processing CSV file")
                    return JsonResponse({'error': f'Error processing CSV file: {str(e)}'}, status=500)
            else:
                return JsonResponse({'error': 'File format not supported. Please upload a CSV file.'}, status=400)
        else:
            return JsonResponse({'error': 'Form is not valid'}, status=400)
    else:
        return JsonResponse({'error': 'Invalid request'}, status=400)



@login_required(login_url='/')
def exports_to_csv(request):
    checked_username = None
    senderName = None

    try:
        # Get all notifications sent to the current user that have been read
        read_notifications = Notification.objects.filter(receiver=request.user, is_read=True)

        for notification in read_notifications:
            sender_username = notification.sender.username
            receiver_username = notification.receiver.username

            staff_senders = CustomUser.objects.filter(username=sender_username, is_staff=True)
            normal_user = get_object_or_404(CustomUser, username=receiver_username, is_staff=False)

            for user in staff_senders:
                sender = user.username

                try:
                    senderName = get_object_or_404(CustomUser, username=sender, is_staff=True)
                    receiverName = get_object_or_404(CustomUser, username=normal_user.username, is_staff=False)

                    if receiverName and senderName:
                        checked_username = receiverName.username
                except Exception as user_error:
                    return HttpResponse(status=500)

        if checked_username == str(request.user):
            target_user = senderName
        else:
            target_user = request.user

        response = HttpResponse(content_type='text/csv')

templates/invclc/check.html
{% extends 'base.html' %} 
{% load custom_filters %}
{% load static %} 

{% block title %} MedRegiA || Check {{user_title}} {% endblock title %} 

{% block nav_footer %}{% static 'nav_footer.css' %} {%endblock nav_footer %} 

{% block link %}{% static 'invclc/css/check.css' %} {%endblock link %}

{% block side %}{% static 'invclc/css/static_sidebar.css' %}{% endblock side %}


{% block navbar %} 
    {% include 'nav.html' %} 
{% endblock navbar%} 

{% block sidebar %}
{% include 'sidebar.html' %}
{% endblock sidebar %}



{% comment %} 
<td class="pharmacystatus">
   {% if data.pharmacy_name %}
       {{ data.pharmacy_name|convert_medical }}<span class="loginstatus"></span>
   {% else %}
       Not Found
   {% endif %}
</td> {% endcomment %}
{% block content %}
{% for invoice in invoices %}
  <div class="main-container">
    <div class="main-header">
      <div class="check-container-btn"></div>
      <h2 class="heading">{{invoice.pharmacy_name}}</h2>
      <div class="check-container-btn"><button type="button" class="csvBtn">Print CSV</button></div>
      {% comment %} <div class="check-container-btn"><button type="button" class="csvBtn">Print CSV</button></div> {% endcomment %}
    </div>
    <div class="main-body">
      <div class="main-body-left">
        <h4>Invoice Number : {{invoice.invoice_number}} </h4>
        <h4>Invoice Date : {{invoice.invoice_date}}</h4>
      </div>

      <div class="main-body-center">
        <h4>Invoice Amount</h4>
        <h4>{{invoice.invoice_amount}}</h4>
      </div>

      <div class="main-body-right">
        <h4>Updated Date : {{invoice.today_date}}</h4>
        <div class="status">
          <h4>Current Medical :{{store}}</h4>
          <h4>Invoice Medical :
          {% if invoice.pharmacy_name %}
              {{ invoice.pharmacy_name|convert_medical }}<span class="loginstatus"></span>
          {% else %}
              Not Found
          {% endif %}</h4>
        </div>
      </div>
    </div>

    <div class="main-bottom">
      <table>
        <thead>
          <tr>
            <th>Paid Date</th>
            <th>Paid Details</th>
          </tr>
        </thead>
        <tbody>
          {% for tracking_invoice in tracking_invoices %}
          {% if tracking_invoice.Bill_no == invoice.invoice_number %}
          <tr>
            <td>{{ tracking_invoice.payment_date }}</td>
            <td>{{ tracking_invoice.paying_amount }}</td>
          </tr>
          {% endif %}
          {% endfor %}
        </tbody>
      </table>      
    </div>

    <div class="main-footer">
      <h4 class="full-paid">Status : Full Paid</h4>
      <button type="button" onclick = "window.print()">Print/pdf</button>
    </div>
</div>
{% endfor %}
<script src="{% static 'invclc/js/check.js' %}"></script>
<script src="{% static 'invclc/js/check_sidebar.js' %}"></script>


{% endblock content %}

templates/invclc/checkmore.html
{% extends 'base.html' %} 
{% load custom_filters %}
{% load static %} 

{% block title %} MedRegiA || Check More {% endblock title %} 

{% block nav_footer %}{% static 'nav_footer.css' %} {%endblock nav_footer %} 

{% block link %}{% static 'invclc/css/checkmore.css' %} {%endblock link %}

{% block side %}{% static 'invclc/css/static_sidebar.css' %}{% endblock side %}

{% block navbar %} 
    {% include 'nav.html' %} 
{% endblock navbar%} 

{% block sidebar %}
{% include 'sidebar.html' %}
{% endblock sidebar %}

{% block content %}
    <div class="checkmore-container">
        <h3> Paid record More details</h3>
        <div class="checkmore-container-paid">
            <div class="checkmore-container-btn"><button type="button" class="csvBtn">Print CSV</button></div>
            <div class="table-container">
                <table class="checkmoreTable">
                    <thead>
                        <tr>
                            <th><input type="checkbox"></th>
                            <th>Pharmacy Name</th>
                            <th>Invoice Number</th>
                            <th>Invoice Date</th>
                            <th>Updated Date</th>
                            <th>Invoice Amount</th>
                            <th>Paid Details</th>
                            <th>Paid Date</th>
                            <th colspan="2">Status</th>
                            <th>Records</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for data in invoices %}
                            <tr>
                                <td><input type="checkbox" id="check"></td>
                                <td>{{ data.pharmacy_name }}</td>
                                <td>{{ data.invoice_number }}</td>
                                <td>{{ data.invoice_date }}</td>
                                <td>{{ data.today_date }}</td>
                                <td class="invoice-amount">{{ data.invoice_amount }}</td>
                                <td class="paid-details">
                                    <div class="scrollable-cell">
                                        {% for tracking_invoice in tracking_invoices %}
                                            {% if tracking_invoice.Bill_no == data.invoice_number %}
                                                {{ tracking_invoice.paying_amount }}
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                </td>
                                <td class="paid-details">
                                    <div class="scrollable-cell expand">
                                        {% for tracking_invoice in tracking_invoices %}
                                            {% if tracking_invoice.Bill_no == data.invoice_number %}
                                                {{ tracking_invoice.payment_date }}
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                </td>
                                <td class="medicalstatus">{{ MedicalStatus }} <span class="status"></span></td>
                                <td class="pharmacystatus">
                                    {% if data.pharmacy_name %}
                                        {{ data.pharmacy_name|convert_medical }}<span class="loginstatus"></span>
                                    {% else %}
                                        Not Found
                                    {% endif %}
                                </td>
                                <td><a href="../check/{{ data.id }}"><button type="button" class="check_btn">Check</button></a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script src="{% static 'invclc/js/checkmore.js' %}"></script>
    <script src="{% static 'invclc/js/checkmore_sidebar.js' %}"></script>
{% endblock content %}

templates/invclc/create.html
{% extends "base.html" %} 
{% load static %} 

{% block link %}{% static 'invclc/css/create.css' %} {% endblock link %} 
{% block link2 %}{% static 'nav_footer.css' %} {% endblock link2 %}

{% block navbar %}
    {% include 'nav.html' %} 
{% endblock navbar %}

{% block message %}
 {% include 'invoice_message.html' %}
{% endblock message %}

{% block content %}
<div class="create-container">
  {% comment %} <h3>Create</h3> {% endcomment %}
  <form action="" method="post">
      {% csrf_token %}
    <div class="inputdetails">
      <label>Pharmacy name :</label>
      {{form.pharmacy_name}}
    </div>
    <div class="inputdetails">
      <label>Invoice Number :</label>
      {{form.invoice_number}}
    </div>
    <div class="inputdetails">
      <label>Invoice Date :</label>
      {{form.invoice_date}}
    </div>
    <div class="inputdetails">
      <label>invoice Amount :</label>
      {{form.invoice_amount}}
    </div>

    <div class="inputdetails">
      <label>Payment Amount :</label>
      {{form.payment_amount}}
    </div>

    <div class="inputdetails">
      <label>Balance Amount :</label>
      {{form.balance_amount}}
    </div>
      {{form.today_date}}
    <div class="back_btn">
      <button type="submit">Save</button>
    </div>
    <div class="navigate">
      <a href="{% url 'index' %}">Back to Invoice</a>
    </div>
  </form>
</div>

<script>
  const invoice_amount = document.querySelector(".invoice_amount");
  const payment_amount = document.querySelector(".payment_amount");
  const balance_amount = document.querySelector(".balance_amount");
  
  invoice_amount.addEventListener("input", calculate);
  payment_amount.addEventListener("input", calculate);
  
  function calculate() {
    let invoice = Number(invoice_amount.value);
    let payment = Number(payment_amount.value);
    let balance = invoice - payment;
  
    if (balance < 0) {
      balance_amount.value = "Amount Not Valid";
      balance_amount.style.backgroundColor = "red";
      balance_amount.style.color = "#FFFF";
    } else if (
      Number(invoice_amount.value) !== 0 &&
      Number(payment_amount.value) !== 0 &&
      Number(invoice_amount.value) == Number(payment_amount.value)
    ) {
      balance_amount.value = "Paying Full Amount ";
      balance_amount.style.backgroundColor = "green";
      balance_amount.style.color = "#FFFF";
    } else {
      balance_amount.value = `₹ ${balance}`;
      balance_amount.style.backgroundColor = "#d3d3d3";
      balance_amount.style.color = "black";
    }
  }

</script>
<script src="{% static 'invclc/js/index.js' %}"></script>
{% endblock content %}

templates/invclc/delete.html
{% extends 'base.html' %} 

{% load static %} 

{% block title %} MedRegiA || Delete History {% endblock title %} 

{% block nav_footer %}{% static 'nav_footer.css' %} {%endblock nav_footer %} 

{% block link %}{% static 'invclc/css/delete.css' %} {%endblock link %}

{% block navbar %} 
    {% include 'nav.html' %} 
{% endblock navbar%} 


{% block content %}
<div class="main-container">
    <h2 class="heading">Delete Page</h2>
    <hr>
        <form action="">
          <div class="table-container">
            <table>
                <thead>
                    <tr>
                        <th>Pharamacy Name</th>
                        <th>Invoice Number</th>
                        <th>Invoice date</th>
                        <th>Amount</th>
                        <th>Balance</th>
                        <th>due Pay</th>
                        <th>Action</th>
                    </tr>
                </thead>

                  <tbody>
                    {% for i in invoices %}
                    <tr>
                      <td>{{ i.pharmacy_name }}</td>
                      <td>{{ i.invoice_number }}</td>
                      <td>{{ i.invoice_date }}</td>
                      <td>₹{{ i.invoice_amount }}</td>
                      <td>₹{{ i.balance_amount }}</td>
                      <td>₹{{ i.payment_amount }}</td>
                      <td>
                        <a href="../delete_view/{{i.id}}"><button type="button" class="btn"> Delete</button> </a>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
            </table>
        </form>
    </div>
{% endblock content %}

templates/invclc/edit.html
{% extends 'base.html' %}
{% load static %}
{% block nav_footer %}{% static 'nav_footer.css' %} {% endblock nav_footer %}
{% block link %}{% static 'invclc/css/edit.css' %} {% endblock link %}

{% block title %} Editing {{invoice.pharmacy_name}} {% endblock title %}
{% block navbar %}
  {% include 'nav.html' %}
{% endblock navbar %}

{% block message %}
  {% include 'message.html' %}
{% endblock message %}

    {% block content %}
    <div class="invoice-user">
        <h2>Editing {{invoice.pharmacy_name}}</h2>
        <form action="" method="post">
            {% csrf_token %}

            <div class="pharmacy invoice">
                <label for="id_pharmacy_name">Pharmacy Name</label>
                <input type="text" name="pharmacy_name" id="id_pharmacy_name" value="{{invoice.pharmacy_name}}">
            </div>

            <div class="invoice-number invoice">
                <label for="id_invoice_number">Invoice Number</label>
                <input type="text" name="invoice_number" id="id_invoice_number" value="{{invoice.invoice_number}}">
            </div>
            
            <div class="invoice-date invoice">
                <div class="instruction">
                <label for="id_invoice_date">Invoice Date</label> 
                <small>DD/MM/YYYY or DD-MM-YYYY (Formate)</small>
                </div>
                <input type="text" name="invoice_date" id="id_invoice_date" value="{{invoice.invoice_date}}">
            </div>
           

            <div class="invoice-Amount invoice">
                <label for="id_invoice_amount">Invoice Amount</label>
                <input type="text" name="invoice_amount" id="id_invoice_amount" value="{{invoice.invoice_amount}}">
            </div>
            
            <div class="due-pay invoice">
                <label for="id_payment_amount">Due Pay</label>
                <input type="text" name="payment_amount" id="id_payment_amount" value="{{invoice.payment_amount}}">
            </div>
            
            <div class="today-date invoice">
                <label for="id_today_date">today date</label>
                <input type="date" name="today_date" id="id_today_date" value="{{invoice.today_date}}">
            </div>   

            <button type="submit">Make the Changes</button>

        </form>
        
        <a href="{% url 'index' %}">Back to Index</a>
    </div>
        


    {% endblock %}