authentication/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view, name='login'),
    # path('login/', views.login_view, name='login'),
    path('phone_login/', views.phone_login_view, name='phone_login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'), 
    path('confirm_admin/<str:uniqueid>',views.confirm_admin, name='confirm_admin'),
    path('admin_cancel/<str:uniqueid>',views.admin_cancel, name='admin_cancel'),
    
    # path('home/', views.home_page, name='home'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/<int:state_id>/<int:district_id>/<int:districtId>', views.profile_view, name='profile'),
    path('change_pin/', views.change_pin, name='change_pin'),
    path('colaborator/',views.colaborator_list, name='colaborator'),
    # path('payment_home/', views.payment_view, name='payment_home'),

    path('clinic/', views.clinic_page, name='clinic'),

    #admin
    path('admin/', views.admin_page, name='admin'),

    # password change
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('get-states/', views.get_states, name='get_states'),
    path('get-districts/', views.get_districts, name='get_districts'),
    path('get-districts/<int:state_id>/', views.get_districts, name='get_districts_by_state'),

    #Forget Password Change
    path('reset_password/', auth_views.PasswordResetView.as_view(), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    # path('accounts/login/', auth_views.LoginView.as_view(template_name='authentication/login.html'), name='login'),
     path('all_notification/', views.all_notification, name='all_notification'), 
]

invclc/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('index/', views.index_view, name='index'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('update_invoice/<int:invoice_id>/', views.update_invoice, name='update_invoice'),
    path('delete_invoice/<int:invoice_id>/', views.delete_invoice, name='delete_invoice'),
    path('pay_invoice/<int:invoice_id>/', views.pay_invoice, name='pay_invoice'),
    path('payment_invoice/<int:payment_id>/', views.payment_invoice, name='payment_invoice'),
    # path('entry/',views.entrydata, name="entry"),
    path('update/', views.update_view, name='update'),
    path('delete/', views.delete_page, name='delete'),
    path('check/<int:id>', views.check_view, name='check'),
    path('statics/', views.staticspage_view, name='statics'),
    # path('create/', views.create_view, name='create'),
    path('update_view/<int:pk>/', views.update_view, name='update'),
    # path('payment/<int:payment_id>',views.payment_view, name="payment"),
    # path('edit/<int:id>',views.edit_view, name='edit'),
    # path('delete_view/<int:pk>/', views.delete_view, name='delete_view'),
    path('import-export/', views.import_view, name='import-export'),
    
    path('csv/', views.exports_to_csv, name='exports_to_csv'),
    path('xlsx/', views.exports_to_xlsx, name='exports_to_xlsx'),
    path('json/', views.exports_to_json, name='exports_to_json'),
    
    path('checkmore/', views.checkmore_view, name='checkmore'),
    path('paymore/', views.paymore_view, name='paymore'),
    path('updatemore/', views.updatemore_view, name='updatemore'),
    path('unpaid_debt/', views.unpaid_debt, name='unpaid_debt'),

    path('upload_csv/', views.upload_csv, name='upload_csv'),
    path('empty_csv/',views.empty_csv,name='empty_csv'),
    path('empty_xlsx/',views.empty_xlsx,name='empty_xlsx'),
    path('adminacess/',views.admin_access,name='adminacess'),
    path('invite/',views.invite_user,name='invite'),
    
    path('process_invite/',views.process_invite,name='process_invite'),
    
    path('connect/',views.connect_view,name='connect'),
    path('create_medical/',views.create_medical_record,name="create_medical"),
    path('search/',views.medical_search,name="medical_search"),

    path('get_yearly_data/', views.get_yearly_data, name='get_yearly_data'),
    path('get_monthly_data/', views.get_monthly_data, name='get_monthly_data'), 
    path('get_total_sum/', views.get_total_sum, name='get_total_sum'),
    path('api/data', views.get_data, name='get_data'),

]

medregia/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('authentication.urls')),
    path('',include('invclc.urls')),   
]

authentication/models.py
# models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone
import pytz

class StateModel(models.Model):
    Pid = models.IntegerField(primary_key=True)
    LocationType = models.CharField(max_length=100)
    Pname = models.CharField(max_length=100)
    
    def __str__(self):
        return self.Pname
   
class DistrictModel(models.Model):
    id = models.IntegerField(primary_key=True)
    state = models.ForeignKey(StateModel, on_delete=models.CASCADE,null=True)
    Pid = models.IntegerField()
    LocationType = models.CharField(max_length=100)
    districtname = models.CharField(max_length=100)
    
    def __str__(self):
        return self.districtname
        
class CustomUser(AbstractUser):
    STORE_TYPES = [
        ('retailer', 'Retailer'),
        ('manufacturer', 'Manufacturer'),
        ('pharmacy', 'Pharmacy'),
        ('medical', 'Medical'),
        ('others', 'Others'),
    ]

    POSITION_CHOICES = [
        ('Admin', 'Admin'),
        ('Senior', 'Senior'),
        ('Member', 'Member'),
        ('NewUser', 'NewUser')
    ]

    username = models.CharField(max_length=150, unique=True, verbose_name='Username')
    phone_num = models.CharField(max_length=15, blank=True, verbose_name='Phone Number',unique=True)
    email = models.EmailField(unique=True, verbose_name='Email')
    pin = models.PositiveIntegerField(blank=True, null=True, verbose_name='PIN')
    
    store_type = models.CharField(max_length=50, choices=STORE_TYPES, null=True, blank=True, verbose_name='Store Type')
    other_value = models.CharField(max_length=50, null=True, blank=True, verbose_name='Other Value')
    position = models.CharField(max_length=20, choices=POSITION_CHOICES, null=True, blank=True, default="Admin", verbose_name='Position')

    groups = models.ManyToManyField(
        'auth.Group',
        related_name='customuser_set',
        blank=True,
        verbose_name='Groups',
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='customuser_set',
        blank=True,
        verbose_name='User Permissions',
        help_text='Specific permissions for this user.',
    )
    
    # class Meta:
    #     permissions = [
    #         ("view_own_details", "Can view own details"),
    #     ]
    
    def __str__(self):
        return self.username
    
class Person(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, null=True)
    MedicalShopName = models.CharField(max_length=100, blank=True, null=True )
    ProprietaryName = models.CharField(max_length=100, blank=True, null=True ,unique = True)
    ProprietaryNumber = models.CharField(max_length=100, blank=True, null=True ,unique = True)
    ProprietaryContact = models.CharField(max_length=100, blank=True, null=True ,unique = True)
    DrugLiceneseNumber2 = models.CharField(max_length=100, blank=True, null=True,unique = True)
    DrugLiceneseNumber1 = models.CharField(max_length=100, blank=True, null=True ,unique = True)

    # Registered Address
    state = models.ForeignKey(StateModel, on_delete=models.SET_NULL, null=True, blank=True)
    district = models.ForeignKey(DistrictModel, on_delete=models.SET_NULL, null=True, blank=True)
    City = models.CharField(max_length=100, blank=True, null=True)
    Pincode = models.CharField(max_length=100, blank=True, null=True)
    StreetNumber = models.CharField(max_length=100, blank=True, null=True)
    DoorNumber = models.CharField(max_length=100, blank=True, null=True)

    PharmacistName = models.CharField(max_length=100, blank=True, null=True)
    RegisteredNumber = models.CharField(max_length=100, blank=True, null=True ,unique = True)
    ContactNumber = models.CharField(max_length=15, blank=True, null=True)
    PharmacistEmail = models.EmailField(blank = True,null=True)

    UniqueId = models.CharField(max_length=100, blank=True, null=True)
    temporaryNo = models.CharField(max_length=50,blank=True,null=True)

    def __str__(self):
        MedicalShopName = self.MedicalShopName or ''
        return MedicalShopName
    
class Notification(models.Model):
    sender = models.ForeignKey(CustomUser, related_name='sent_notifications', on_delete=models.CASCADE)
    receiver = models.ForeignKey(CustomUser, related_name='received_notifications', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    message = models.TextField(default = "Notification")
    is_read = models.BooleanField(default=False)
    request_status = models.BooleanField(default = True)
    position = models.CharField(max_length = 20,null=True)
        
    class Meta:
        unique_together = ('sender', 'receiver')
    
    def __str__(self):
        return f"Notification from {self.sender.username} to {self.receiver.username}"
    
class ConnectMedicals(models.Model):
    request_sender = models.ForeignKey(CustomUser, related_name='request_sender', on_delete=models.CASCADE)
    request_receiver = models.ForeignKey(CustomUser, related_name='request_receiver', on_delete=models.CASCADE)
    sender_name = models.CharField(max_length=30, editable=True, null=True)  # New field to store sender's username
    is_read = models.BooleanField(default=False)
    accept_status = models.BooleanField(default=True)
    status_message = models.CharField(max_length=30, null=True, blank=True)
    request_message = models.TextField(null=True, blank=True)
    timestamp = models.DateTimeField(null=True, blank=True)
    

    def save(self, *args, **kwargs):
        # Set the sender_name before saving the model
        self.sender_name = self.request_sender.username

        # Set the timestamp to the desired timezone if not already set
        if not self.timestamp:
            ist = pytz.timezone('Asia/Kolkata')
            self.timestamp = timezone.now().astimezone(ist)

        super().save(*args, **kwargs)
        print(self.timestamp)

    def __str__(self):
        return f"Notification from {self.request_sender.username} to {self.request_receiver.username}"

    
class RegisterMedicals(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name='register_medicals',null=True)
    Medical_name = models.CharField(max_length=50)
    dl_number1 = models.CharField(max_length=30)
    dl_number2 = models.CharField(max_length=30)
    UniqueId = models.CharField(max_length = 100 , null=True)
    medical_timestamp = models.DateTimeField(auto_now_add=True)

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from .models import CustomUser
from django.core.validators import MaxValueValidator
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):
    username = forms.CharField(
        max_length=50, 
        widget=forms.TextInput(attrs={'placeholder': 'Enter Your Username', 'autocomplete': 'off'})
    )
    phone_num = forms.IntegerField(
        widget=forms.NumberInput(attrs={'placeholder': 'Enter your phone number'})
    )
    pin = forms.IntegerField(
        widget=forms.NumberInput(attrs={'placeholder': 'Enter your pin'}),
        validators=[MaxValueValidator(9999)]
    )
    STORE_TYPES = [
        ('', 'Select'),
        ('retailer', 'Retailer'),
        ('manufacturer', 'Manufacturer'),
        ('pharmacy', 'Pharmacy'),
        ('medical', 'Medical'),
        ('others', 'Others'),
    ]
    store_type = forms.ChoiceField(choices=STORE_TYPES)
    other_value = forms.CharField(
        max_length=50, 
        widget=forms.TextInput(attrs={'placeholder': 'Categories'}), 
        required=False
    )

    email = forms.EmailField(
        max_length=200, 
        help_text='Required', 
        widget=forms.EmailInput(attrs={'placeholder': 'Enter your email', 'value': '@gmail.com'})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Enter your password'})
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Repeat your password'})
    )

    class Meta:
        model = CustomUser
        fields = UserCreationForm.Meta.fields + (
            'email', 'password1', 'password2', 'phone_num', 'pin', 'store_type', 'other_value',
        )

    def clean(self):
        cleaned_data = super().clean()
        store_type = cleaned_data.get('store_type')
        other_value = cleaned_data.get('other_value')

        if store_type == 'others' and not other_value:
            self.add_error('other_value', "Need some text in the other value field when Others is selected.")
            self.add_error('store_type',"Need Some Text in Other Value Field ")

        

class InsensitiveAuthentication(AuthenticationForm):
    def clean_username(self):
        username = self.cleaned_data.get('username')
        if username:
            try:
                user = CustomUser.objects.get(username__iexact=username)
                if user.username == username:
                    return username
            except CustomUser.DoesNotExist:
                pass
        raise forms.ValidationError("Invalid username is not Valid")

        

templates/authentication/all_notification.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% block title %} MedRegiA || All Notifications {% endblock title %}
{% block nav_footer %}{% static 'nav_footer.css' %} {% endblock nav_footer %}
{% block link2 %}{% static 'authentication/css/all_notification.css' %} {% endblock link2 %}
{% block side %}{% static 'authentication/css/sidebar.css' %}{% endblock side %}
{% block link_footer %}{% static 'footer.css' %} {% endblock link_footer %}

{% block navbar %}
{% include 'nav.html' %}
{% endblock navbar %}


{% block sidebar %}
{% include 'sidebar.html' %}
{% endblock sidebar %}

{% block message %}
{% include 'invoice_message.html' %}
{% endblock message %}

{% block content %}

<div class="notification-body">
    <h1>Page Under Maintance <br>
        Coming soon...</h1>
</div>

{% endblock content%}

templates/authentication/all_notifications.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% block title %} MedRegiA || Invoice {% endblock title %}
{% block nav_footer %}{% static 'nav_footer.css' %} {% endblock nav_footer %}
{% block link2 %}{% static 'invclc/css/index.css' %} {% endblock link2 %}
{% block side %}{% static 'authentication/css/sidebar.css' %}{% endblock side %}
{% block link_footer %}{% static 'footer.css' %} {% endblock link_footer %}

{% block navbar %}
{% include 'nav.html' %}
{% endblock navbar %}


{% block sidebar %}
{% include 'sidebar.html' %}
{% endblock sidebar %}

{% block message %}
{% include 'invoice_message.html' %}
{% endblock message %}

{% block content %}
    <p>Update Comming Soon </p>
{% endblock content %}

templates/authentication/change_pin.html
{% extends 'base.html' %}
{% load static %}
{% block title %} MedRegiA || Change_pin {% endblock title %}
{% block nav_footer %}{% static 'nav_footer.css' %} {% endblock nav_footer %}
{% block link %}{% static 'authentication/css/changepin.css' %} {% endblock link %}
{% comment %} {% block side %}
    {% static 'authentication/css/sidebar.css' %}
{% endblock side %} {% endcomment %}

{% block navbar %}
  {% include 'nav.html' %}
{% endblock navbar %} 

{% block message %}
  {% include 'message.html' %}
{% endblock message %}

{% block content %}
<div class="body-container">
  <div class="container">
    <h1>Change PIN</h1>
    <form method="post" action=''>
      {% csrf_token %}
        <div class="form-group">
            <label for="current-pin">Current PIN:</label>
            <input type="password" name="current_pin" oninput="validateInput()" id="current_pin" required>
        </div>
        <div class="form-group">
            <label for="new-pin">New PIN:</label>
            <input type="password" name="new_pin" oninput="validateInput()" id="new_pin" required>
        </div>
        <div class="form-group">
            <label for="confirm-new-pin">Confirm New PIN:</label>
            <input type="password" name="confirm_new_pin" oninput="validateInput()" id="confirm_new_pin" required>
        </div>
        <div class="buttons">
          <button type="submit" class="change-btn">Change PIN</button>
          <a href="{% url 'adminacess' %}"><button type="button" class="back-btn">Back</button></a>    
        </div>
    </form>
  </div>
</div>


<script>
  function validateInput() {
    let currentPin = document.getElementById("current_pin");
    let newPin = document.getElementById("new_pin");
    let confirmNewPin = document.getElementById("confirm_new_pin");
    
    currentPin.value = currentPin.value.replace(/[^0-9]/g, "");
    newPin.value = newPin.value.replace(/[^0-9]/g, "");
    confirmNewPin.value = confirmNewPin.value.replace(/[^0-9]/g, "");
    
    if (currentPin.value.length > 4) currentPin.value = currentPin.value.slice(0, 4);
    if (newPin.value.length > 4) newPin.value = newPin.value.slice(0, 4);
    if (confirmNewPin.value.length > 4) confirmNewPin.value = confirmNewPin.value.slice(0, 4);
  }
  </script>
 
{% endblock content %}

templates/authentication/clinic.html
{% extends 'base.html' %}
{% load static %}
{% block title %} MedRegiA || Clinic {% endblock title %}
{% block link %} {% static 'authentication/css/clinic.css' %} {% endblock link %}
{% block side %}{% static 'authentication/css/sidebar.css' %}{% endblock side %}
{% block nav_footer %}{% static 'nav_footer.css' %} {% endblock nav_footer %}

{% block navbar %}
{% include 'nav.html' %}
{% endblock navbar %}

{% block sidebar %}
{% include 'sidebar.html' %}
{% endblock sidebar %}

{% block content %}
<div class="vh">
    <div>
     <div class="wrap">
      <h1>Webpage under Maintenance</h1>
      <h2><p>Sorry for the inconvenience.<br>Our website is currently undergoing scheduled maintenance.<br><br></p></h2>
      <p>Thank you for your understanding.</p>
      </div>
      <a href="{% url 'index' %}"><button class="glow-on-hover" type="button">Back To Home</button></a>
    </div>
</div>

{% endblock content%}

templates/authentication/colaborator.html
  {% extends 'base.html' %}
{% load static %}
{% block title %} MedRegiA || Coloborator Lists {% endblock title %}
{% block nav_footer %}{% static 'nav_footer.css' %} {% endblock nav_footer %}
{% block link %}{% static 'authentication/css/coloborator.css' %} {% endblock link %}

{% block navbar %}
  {% include 'nav.html' %}
{% endblock navbar %} 

{% block message %}
  {% include 'message.html' %}
{% endblock message %}

{% block content %}
    <h2 class="head">Coloborator list with Other User</h2>
    <div class="coloborate">
      {% if colaborator%}
        <div class="listbox">
            <h2>Collaborate list</h2>
            {% for coloborators in colaborator %}
              <ul>
                  <li><span>{{coloborators.id}}</span>{{coloborators.sender}}</li>
              </ul>
            {% endfor %}
        </div>
      {% else %}
        <div class="listbox">
           <p>No Coloborator Found</p>
        </div>
      {% endif %}
    </div>
 
{% endblock content %}

templates/authentication/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %} MedRegiA || Login {% endblock title %}
{% block link %} {% static 'authentication/css/login.css' %} {% endblock link %}

{% block message %}
  {% include 'message.html' %}
{% endblock message %}

{% block content %}



  <div class="login-container">
    <div class="login-header">
      <div class="login-header-about">
        <a href="#">About Us</a>
      </div>

      <div class="login-header-medregia">
        <a href="{% url 'login' %}"> MedRegiA</a>
      </div>

      <div class="login-header-admin">
        <a href="{% url 'admin' %}"> Admin Site<span><i class="fa-solid fa-arrow-right"></i></span></a>
      </div>
      
    </div>

    <div class="login-container-body">
      <div class="container-body-messages">
        <div class="messages-mission">
          <h3>Mission</h3>
          <p> To guide small-scale businessmen in the medical field and strongly support them for business development, ultimately contributing to the success of their ventures.</p>
        </div>

        <div class="messages-vision">
          <h3>Vision</h3>
          <p> To foster successful businesses in the medical sector, recognizing that each small business contributes significantly to the growth and prosperity of our nation.</p>
        </div>
      </div>

      <div class="container-body-login">
        {% if form.errors %}
        <div class="alert alert-danger">
            {{ form.errors }}
            <i class="fas fa-times disable"></i>
        </div>
        {% endif %}
        <div class="login-body-container">
          <div class="login-body-header">
            <h3>Login Page</h3>

            <div class="phone">
              <a href="{% url 'phone_login' %}"><i class="fa-solid fa-mobile-screen-button" title="phone login"></i></a>
            </div>
          </div>

          <div class="body-container-login">
            <form action="#" method="post">
              {% csrf_token %}
              <div class="login-username">
                <label for="id_username">Username</label>
                {{form.username}}
              </div>

              <div class="login-password">
                <label for="id_password">Password</label>
                {{form.password}}
              </div>

              <div class="login-buttons">
                <div class="login-btn">
                  <a href="#"><button type="submit" class="loginbtn">Login</button></a>
                </div>
  
                <div class="signup-btn">
                  <a href="{% url 'signup' %}"> <button type="button" class="signupbtn">SignUp</button></a>
                </div>
              </div>
            </form>
          </div>

          <div class="bottom-field">
            <a href="{% url 'reset_password' %}">Forget Password ?</a>
            <a href="#">Terms & Conditions</a>
          </div>

        </div>
      </div>
    </div>

  </div>

<script src="{% static 'authentication/js/login.js' %}"></script>
{% endblock content %}

templates/authentication/signup.html
{% extends 'base.html' %}
{% load static %}
{% block title %} MedRegiA || signup {% endblock title %}
{% block link %} {% static 'authentication/css/signup.css' %} {% endblock link %}

{% block message %}
  {% include 'message.html' %}
{% endblock message %}

{% block content %}


<div class="signup-header">

  <div class="signup-header-medregia">
    <a href="{% url 'login' %}"> MedRegiA</a>
  </div>
</div>

<div class="container">
  
  <div class="arrow">
    <a href="{% url 'login'%}"><span><i class="fa-solid fa-arrow-left"></i></span></a>
  </div>

    <div class="header">
      <h1>Sign Up</h1>
    </div>
    <form action="" method="post">
        {% csrf_token %}
      <div class="form-group">
        <label for="id_username">Username</label>
        {{form.username}}
        <span>
            {% if form.errors.username %}
                {{form.errors.username}}
            {% endif %}
        </span>
      </div>
      <div class="form-group">
        <label for="id_email">Email</label>
        {{form.email}}
        <span>
          {% if form.errors.email %}
              {{form.errors.email}}
          {% endif %}
      </span>
      </div>

      <div class="form-group">
        <label for="id_password1">Password</label>
        {{form.password1}}
        <span>
          {% if form.errors.password1 %}
              {{form.errors.password1}}
          {% endif %}
      </span>
      </div>
      
      <div class="form-group">
        <label for="id_password2">Confirm Password</label>
        {{form.password2}}
        <span>
          {% if form.errors.password2 %}
              {{form.errors.password2}}
          {% endif %}
      </span>
      </div>

      <div class="form-group">
        <label for="id_phone_num">Phone Number</label>
        {{form.phone_num}}
        <span>
          {% if form.errors.phone_num %}
              {{form.errors.phone_num}}
          {% endif %}
      </span>
      </div>

      <div class="form-group">
        <label for="id_pin">Pin</label>
        {{form.pin}}
        <span>
          {% if form.errors.pin %}
              {{form.errors.pin}}
          {% endif %}
      </span>
      </div>

      <div class="form-group selection">
        <label for="id_store_type">Categories</label>
        {{form.store_type}}
        <span>
          {% if form.errors.store_type %}
              {{form.errors.store_type}}
          {% endif %}
      </span>
      </div>
      <div class="form-group others">
        <label for="id_other_type" class="label-other">Others</label>
        {{form.other_value}}
        <span>
          {% if form.errors.other_value %}
              {{form.errors.other_value}}
          {% endif %} 
      </span> 
      </div>
      <div class="button-submit">
        <button type="submit" class="btn">Signup</button>
      </div>
      <div class="signup-bottom-field">
        <a href="#">Terms & conditions</a>
      </div>
    </form>
</div>

<script src="{% static 'authentication/js/signup.js' %}"></script>
{% endblock %}

templates/authentication/welcome_email.html
Dear {{user.username}},

! Welcome {{user.username}}
Welcome aboard! We are thrilled to have you join our community at "MedRegia". As a new member of our platform, you are now part of a growing network of medical professionals dedicated to providing exceptional care and services to patients worldwide.

At "MedRegia", we strive to create a seamless and intuitive platform that empowers medical professionals like yourself to connect, collaborate, and thrive in today's dynamic healthcare landscape. Whether you're looking to expand your professional network, access valuable resources, or stay updated on the latest medical advancements, our platform is here to support you every step of the way.

As you explore "MedRegia", you'll discover a wide range of features and tools designed to enhance your experience and streamline your workflow. From comprehensive patient management solutions to interactive forums and educational resources, we're committed to providing you with the tools and support you need to excel in your practice.

We encourage you to take full advantage of everything our platform has to offer and to engage with our vibrant community of medical professionals. Whether you're seeking advice, sharing insights, or collaborating on research projects, you'll find endless opportunities to connect and grow alongside your peers.

Thank you for choosing "MedRegia" as your trusted partner in healthcare. We're excited to embark on this journey with you and to support you in achieving your professional goals.

If you have any questions or need assistance, please don't hesitate to reach out to our support team. We're here to help!

Once again, welcome to "MedRegia"!

Best regards,
Ishaaq,
General Manager(GM),
MedRegia.